#! /bin/bash
version=`git diff HEAD^..HEAD -- "$(git rev-parse --show-toplevel)"/abcd_version.txt | grep '^\+.*version' | sed -s 's/[^0-9\.]//g'`
echo "found version $version"
if [ "$version" != "" ]; then
    git tag -a "v$version" -m "`git log -1 --format=%s`"
    echo "Created a new tag, v$version"
fi
